import type { NextPage } from "next";
import Head from "next/head";
import { Header } from "@/components/Header";
import { Footer } from "@/components/Footer";
import AssetSection from "@/Section/AssetSection";
import { useTranslation } from "react-i18next";

const Asset: NextPage = () => {
  const { t } = useTranslation("common");

  return (
    <div>
      <Head>
        <title>{t("earn")}</title>
        <meta
          content="Generated by @rainbow-me/create-rainbowkit"
          name="description"
        />
        <link href="/favicon.ico" rel="icon" />
      </Head>
      <Header logo switchTab type="normal" tabType="normal" />
      <AssetSection />
      <Footer />
    </div>
  );
};

export default Asset;
