import type { NextPage } from "next";
import Head from "next/head";
import { Header } from "@/components/Header";
import { Footer } from "@/components/Footer";
import PortfolioSection from "@/Section/PortfolioSection";
import { useTranslation } from "react-i18next";

const Portfolio: NextPage = () => {
  const { t } = useTranslation("common");

  return (
    <div>
      <Head>
        <title>{t("detail")}</title>
        <meta
          content="Generated by @rainbow-me/create-rainbowkit"
          name="description"
        />
        <link href="/favicon.ico" rel="icon" />
      </Head>
      <Header logo switchTab />
      <PortfolioSection type="detail" />
      <Footer />
    </div>
  );
};

export default Portfolio;
