import React from "react";
import Head from "next/head";
import type { NextPage } from "next";
import { Header } from "@/components/Header";
import Banner from "@/components/Banner";
import { Footer } from "@/components/Footer";
import MarketSection from "@/Section/MarketSection";
import RegionBanner from "@/components/RegionBanner";

const Discover: NextPage = () => {
    return (
        <div>
            <Head>
                <title>RainbowKit App - Discover</title>
                <meta
                    content="Generated by @rainbow-me/create-rainbowkit"
                    name="description"
                />
                <link href="/favicon.ico" rel="icon" />
            </Head>
            <Header logo switchTab tabType='normal' />
            <RegionBanner />
            <MarketSection />
            <Footer />
        </div>
    )
}


export default Discover;