import React from "react";
import Head from "next/head";
import type { NextPage } from "next";
import { Header } from "@/components/Header";
import { Footer } from "@/components/Footer";
import MarketSection from "@/Section/MarketSection";
import RegionBanner from "@/components/RegionBanner";
import { useTranslation } from "react-i18next";

const Discover: NextPage = () => {
  const { t } = useTranslation("common");

  return (
    <div>
      <Head>
        <title>{t("discover")}</title>
        <meta
          content="Generated by @rainbow-me/create-rainbowkit"
          name="description"
        />
        <link href="/favicon.ico" rel="icon" />
      </Head>
      <Header logo switchTab tabType="normal" />
      <RegionBanner />
      <MarketSection />
      <Footer />
    </div>
  );
};

export default Discover;
