import type { NextPage } from "next";
import Head from "next/head";
import { Header } from "@/components/Header";
import { Footer } from "@/components/Footer";
import PointsMarketSection from "@/Section/PointsMarketSection";
import { useTranslation } from "react-i18next";
import { useApolloClient, gql } from '@apollo/client';
import useStore  from '@/store/index';
import { useEffect } from "react";

const Market: NextPage = () => {
  const { t } = useTranslation("common");
  const client = useApolloClient();
  const { userInfo,updateIntegralInfo } = useStore();
  // 获取积分信息
  const refetchQuery = async (parms:any) => {
    await client.query({
      query: gql`
      query {
        getUser(input: { 
          address: "${parms.variables}" 
        }) {
          user {
            id
            address
            hashKey
            points
            inviteCode
            createdAt
            updatedAt
            deletedAt
          }
        }
      }
      `
    }).then(res=>{
      updateIntegralInfo(res.data.getUser.user)
    }).catch(error => {
      updateIntegralInfo({})
    });
  };
  useEffect(() => {
    if(!userInfo.address)return
    refetchQuery({
      variables: userInfo.address
    })
  },[])
  return (
    <div>
      <Head>
        <title>{t("points")}</title>
        <meta
          content="Generated by @rainbow-me/create-rainbowkit"
          name="description"
        />
        <link href="/favicon.ico" rel="icon" />
      </Head>
      <Header logo switchTab />
      <PointsMarketSection type="myRewards" />
      <Footer />
    </div>
  );
};

export default Market;
