import type { NextPage } from "next";
import Head from "next/head";
import { Header } from "@/components/Header";
import { Footer } from "@/components/Footer";
import PortfolioSection from "@/Section/PortfolioSection";

const Portfolio: NextPage = () => {
    return (
        <div>
            <Head>
                <title>RainbowKit App - Portfolio</title>
                <meta
                    content="Generated by @rainbow-me/create-rainbowkit"
                    name="description"
                />
                <link href="/favicon.ico" rel="icon" />
            </Head>
            <Header logo switchTab />
            <PortfolioSection type='defi' />
            <Footer />
        </div>
    );
};

export default Portfolio;
