import type { NextPage } from "next";
import Head from "next/head";
import { Header } from "@/components/Header";
import { Footer } from "@/components/Footer";
import { useTranslation } from "react-i18next";

const Privacy: NextPage = () => {
  const { t } = useTranslation("common");

  return (
    <div>
      <Head>
        <title>{t("privacy-title")}</title>
        <meta
          content="Generated by @rainbow-me/create-rainbowkit"
          name="description"
        />
        <link href="/favicon.ico" rel="icon" />
      </Head>
      <Header logo switchTab />
      <section className="bg-bg-primary w-full py-[135px] px-[105px]">
        <h1 className="text-4xl font-bold text-primary mb-8">
          {t("privacy-title")}
        </h1>

        <div className="space-y-6 text-primary">
          {/* Introduction */}
          <div>
            <h2 className="text-md font-500 mb-2 text-primary">
              {t("privacy-intro-title")}
            </h2>
            <p>{t("privacy-intro-content")}</p>
          </div>

          {/* Section 1: The Information We Collect */}
          <div>
            <h2 className="text-md font-500 mb-2 text-primary">
              {t("privacy-collect-title")}
            </h2>
            <p>{t("privacy-collect-content")}</p>
          </div>

          {/* Section 2: Use of Information */}
          <div>
            <h2 className="text-md font-500 mb-2 text-primary">
              {t("privacy-use-title")}
            </h2>
            <p>{t("privacy-use-content")}</p>
          </div>

          {/* Section 3: Disclosure of Information */}
          <div>
            <h2 className="text-md font-500 mb-2 text-primary">
              {t("privacy-disclosure-title")}
            </h2>
            <p>{t("privacy-disclosure-content")}</p>
          </div>

          {/* Section 4: Security */}
          <div>
            <h2 className="text-md font-500 mb-2 text-primary">
              {t("privacy-security-title")}
            </h2>
            <p>{t("privacy-security-content")}</p>
          </div>

          {/* Section 5: Your Rights */}
          <div>
            <h2 className="text-md font-500 mb-2 text-primary">
              {t("privacy-rights-title")}
            </h2>
            <p>{t("privacy-rights-content")}</p>
          </div>

          {/* Section 6: Changes to this Policy */}
          <div>
            <h2 className="text-md font-500 mb-2 text-primary">
              {t("privacy-changes-title")}
            </h2>
            <p>{t("privacy-changes-content")}</p>
          </div>

          {/* Section 7: Contact Us */}
          <div>
            <h2 className="text-md font-500 mb-2 text-primary">
              {t("privacy-contact-title")}
            </h2>
            <p>{t("privacy-contact-content")}</p>
          </div>
        </div>
      </section>
      <Footer />
    </div>
  );
};

export default Privacy;
